# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:              https://wzzju.top
date_format:      "ordinal"
title:            王震的博客
tagline:          '记录生活点滴，分享学习心得'
description:      '自助者天助之 自弃者天弃之'
keywords:         ["AI", "DeepLearning", "Android", "人工智能", "深度学习", "编程", "教程", "学习", "文章" ]
encoding:         "utf-8"
# ---------------- #
#      Jekyll      #
# ---------------- #
markdown:         kramdown
kramdown:
    input:        GFM
highlighter:      rouge
paginate:         5
plugins:             [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-feed, jemoji]
# Permalinks
permalink:        /:year/:month/:day/:title.html
safe: false

author:
  name:           'YuChen'
  url:            https://weibo.com/u/6833407977

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/wzzju/wzzju.github.io
# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
disqus:
    username: yuchen112358
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wzzju
    repo: blog-comments
    oauth:
        client_id: 19e95a40843e60c10539
        client_secret: e54ae9b5f55a2e3b51e8ec897b80c918f335736b
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wzzju
    repo: https://github.com/wzzju/blog-comments
    clientID: e5a8aeb6ac781df840ff
    clientSecret: a65b7ee305064fff7a4da078236e1e12461096a1      
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

