# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wzzju.github.io
date_format: "ordinal"
title: 北冥有鱼
tagline: '记录生活点滴，分享学习心得'
description: '自助者天助之 自弃者天弃之'
keywords: ["AI", "DeepLearning", "Android", "人工智能", "深度学习", "编程", "教程", "学习", "文章" ]
encoding: "utf-8"
# ---------------- #
#      Jekyll      #
# ---------------- #
# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Build settings
paginate: 10
# Permalinks
permalink: pretty
# Exclude files from the _site directory
exclude:
  - README.md
  - new-post.sh
  - run-docker.sh
  - slides-project/
  - talks/slide-src/
  - talks/slide-bgs/
  - assets/exclusion/
# Gem settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

author:
  name: 'YuChen'
  url: http://weibo.com/wzzju

github_username: wzzju
weibo_username: wzzju
facebook_username: wzzju
zhihu_username: yuchen112358

# Custom vars
version: 2.0.0

github:
  repo: https://github.com/wzzju/wzzju.github.io

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: livere
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: wzzju
  repo: blog-comments
  clientID: 481f0b89289da9b8a42b
  clientSecret: 7869eb5965cde657634acbe4bd5a598c5cd350cf
  perPage: 50
  labels: reader-comments
  proxy: https://blog-comments.wzzju.workers.dev/?https://github.com/login/oauth/access_token
# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere:
  livere_uid: MTAyMC81NzIwOC8zMzY3Mg==
# https://utteranc.es
utteranc:
  repo: wzzju/blog-comments
  theme: preferred-color-scheme
  label: reader-comments
